---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  vars:
    expected_content: "I'm Feeling Lucky"
  tasks:
  - name: Assert google.com is reachable
    uri:
      url: http://google.com
      return_content: yes
    register: this

  - name: Assert google.com content type is text/html
    assert:
      that: "'text/html' in this.content_type"
      fail_msg: "Content type retrieved from http://google.com is not 'text/html'!"
      success_msg: "Successfully retrieved http://google.com..."
      quiet: true

  - name: Assert google.com contents are correct
    assert:
      that: "expected_content in this.content"
      fail_msg: "Failed to retrieve http://google.com"
      success_msg: "Successfully retrieved http://google.com"
      quiet: true


 # - name: Debug results
 #   debug:
 #     var: this.content
