---
- name: Ensure required packages are installed
  package:
    update_cache: true
    name:
      - dconf-cli
      - python3-psutil
      - unzip

- name: Ensure user {{ machine_user }} exists
  user:
    name: "{{ machine_user }}"
    shell: /bin/bash
    groups: sudo
    append: true
    password: "$6$cih0/pzm8Clgt9$oto9bUrUBMWCIzer3Wq/g.Rb.yg.D42rA4mqA\
      KElOvyj1gawbeqe0371f4EkEMRWgsls1P.TFFROsKFV.sNwq."

- name: Ensure /home/{{ machine_user }}/.themes exists
  file:
    path: /home/{{ machine_user  }}/.themes
    state: directory
    owner: "{{ machine_user }}"
    group: "{{ machine_user }}"
    mode: 0644

- name: Ensure Solarized Dark theme is installed
  unarchive:
    src: Solarized-Dark-Cyan-3.36_2.0.3.zip
    dest: "/home/{{ machine_user }}/.themes"
    owner: "{{ machine_user }}"
    group: "{{ machine_user }}"
    mode: 0644

- name: Ensure Solarized Dark is the active theme
  community.general.dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    value: "'Solarized-Dark-Cyan-3.36'"
    state: present

- name: Ensure /home/{{ machine_user }}/.local/share/fonts exists
  file:
    path: /home/{{ machine_user }}/.local/share/fonts
    state: directory
    owner: "{{ machine_user }}"
    group: "{{ machine_user }}"
    mode: 0644

# TODO: Figure out how to copy OTF file with spaces intact
- name: Ensure Droid Sans Mono for Powerline font is installed
  get_url:
    url: "https://github.com/powerline/fonts/raw/master/DroidSansMono/Droid%20Sans%20Mono%20for%20Powerline.otf"
    dest: "/home/{{ machine_user }}/.local/share/fonts/Droid-Sans-Mono-for-Powerline.otf"
    owner: "{{ machine_user }}"
    group: "{{ machine_user }}"
    mode: 0444
  notify: "Update font cache"

- name: Ensure that the default terminal profile does not use the system font
  community.general.dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-system-font"
    value: "false"
    state: present

- name: Ensure that the active terminal font is Droid Sans Mono for Powerline
  community.general.dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/font"
    value: "'Droid-Sans-Mono-for-Powerline 18'"
    state: present
