---
- name: Verify
  hosts: all
  gather_facts: false
  become: false

  vars:
    expected_dash_to_dock_settings:
     - key: "autohide"
       value: "false"

     - key: "dash-to-dock"
       value: "false"

     - key: "intellihide"
       value: "false"

  tasks:
  - name: Read Dock settings
    community.general.dconf:
      key: "/org/gnome/shell/extensions/dash-to-dock/{{ item.key }}"
      state: read
    loop: "{{ expected_dash_to_dock_settings|flatten(levels=1) }}"
    register: "actual_dock_settings"

  - name: Verify that the Dock is hidden
    assert:
      that:  "item.item.value == item.value"
      fail_msg: "Expected {{ item.item.key }} to be {{ item.item.value }}, but it is {{ item.value }} instead..."
      success_msg: "{{ item.item.key }} == {{ item.item.value }}"
      quiet: true
    loop: "{{ actual_dock_settings.results | flatten(levels=1) }}"

  - name: Read currently active GTK theme
    community.general.dconf:
      key: "/org/gnome/desktop/interface/gtk-theme"
      state: read
    register: gtk_theme

  - name: Verify Solarized Dark theme is active
    assert:
      that:  "'Solarized-Dark-Cyan-3.36' in gtk_theme.value"
      fail_msg: "Solarized Dark theme not active! gtk_theme.value = {{ gtk_theme.value }}"
      success_msg: "{{ gtk_theme }} is currently active"
      quiet: true

  - name: Read currently active gnome-terminal font
    community.general.dconf:
      key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/font"
      state: read
    register: gnome_terminal_font

  - name: Verify Droid Sans Mono for Powerline is the active font
    assert:
      that:  "'Droid Sans Mono for Powerline 16' in gnome_terminal_font.value"
      fail_msg: "''Droid Sans Mono for Powerline' font not active! gnome_terminal_font.value = {{ gnome_terminal_font.value }}"
      success_msg: "{{ gnome_terminal_font }} is currently active"
      quiet: true

  - name: Read currently active desktop background
    community.general.dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      state: read
    register: gnome_desktop_background

  - name: Verify ropey.jpg is the active desktop background
    assert:
      that:  "'ropey.jpg' in gnome_desktop_background.value"
      fail_msg: "ropey.jpg background not active! gnome_desktop_background.value = {{ gnome_desktop_background.value }}"
      success_msg: "{{ gnome_desktop_background }} is currently active"
      quiet: true
