---
- name: Verify
  hosts: all
  gather_facts: false
  vars_files: "../../defaults/main.yml"
  tasks:
  - name: "Obtain shell for user {{ vm_user_name }}"
    shell:
      cmd: grep "^{{ vm_user_name }}" "/etc/passwd" | cut "-d:" "-f7"
    register: vm_user_shell

  - name: "Verify that the shell for {{ vm_user_name }} is /usr/bin/zsh"
    assert:
      that: "{{ vm_user_shell.stdout_lines[0] == '/usr/bin/zsh' }}"
      fail_msg: "Expected shell for user {{ vm_user_name }} to be /usr/bin/zsh, but it is {{ vm_user_shell.stdout_lines[0] }} instead..."
      success_msg: "{{ vm_user_name }}'s shell is /usr/bin/zsh"
      quiet: true

  - name: "Retrieve status of playbook-created dotfiles"
    stat:
      path: "{{ item }}"
    register: configfiles
    loop:
      - "{{ vm_user_home }}/.gitconfig"
      - "{{ vm_user_home }}/.mrconfig"
      - "{{ vm_user_home }}/.tmux.conf"
      - "{{ vm_user_home }}/.vimrc"
      - "{{ vm_user_home }}/.zshrc"

  - name: "Verify that dotfiles were created correctly"
    assert:
      that:
        - "{{ item.stat.exists }}"
        - "{{ item.stat.isreg }}"
      fail_msg: "{{ item.stat.path }} either does not exist or is not a regular file"
      success_msg: "{{ item.stat.path }} exists and is a regular file"
    loop: "{{ configfiles.results }}"
