---
- name: Verify
  hosts: all
  gather_facts: false
  vars_files: "../../defaults/main.yml"
  tasks:
  - name: "Obtain shell for user {{ vm_user_name }}"
    shell:
      cmd: grep "^{{ vm_user_name }}" "/etc/passwd" | cut "-d:" "-f7"
    register: vm_user_shell

  - name: "Verify that the shell for {{ vm_user_name }} is /usr/bin/zsh"
    assert:
      that: "{{ vm_user_shell.stdout_lines[0] == '/usr/bin/zsh' }}"
      fail_msg: "Expected shell for user {{ vm_user_name }} to be /usr/bin/zsh, but it is {{ vm_user_shell.stdout_lines[0] }} instead..."
      success_msg: "{{ vm_user_name }}'s shell is /usr/bin/zsh"
      quiet: true

  # TODO: Consider add `loop:` here and verifying a few more items (try to do
  # at least one file from each config)
  - name: "Retrieve status of {{ vm_user_home }}.tmux.conf"
    stat:
      path: "{{ vm_user_home }}/.tmux.conf"
    register: tmuxconfig

  - name: "Verify that {{ vm_user_home }}/.tmux.config was created correctly"
    assert:
      that:
        - "tmuxconfig.stat.exists"
        - "not tmuxconfig.stat.isdir"
        - "tmuxconfig.stat.mode == '0755'"
      fail_msg: "{{ vm_user_home }}/.tmux.conf either does not exist, is not a file or has incorrect permissions"
      success_msg: "{{ vm_user_home }}/.tmux.conf exists and has correct permissions"
      quiet: true
